### ISSUE TITLE
Missing Page Route in Admin Setup

### ISSUE THREAD

**Issue by Latitude1969** [mageplaza/magento-2-better-maintenance#17]
Hi All,

I'm missing the Page Route field in my Magento Admin (v. 2.4.1)
Therefor the redirect for Maintenance and Coming Soon does not seem to be working? (Blank Page)

Redirect to all the other (standard pages) works like a charm 👍 

Also the Whitelist Page Link(s) works just fine.

Please help.

Thanks.

Fred.

**Comment by Tuvpt** [comment]
Please download version 2.4 to use.
In addition, the current version has removed the page router field in the configuration section

**Comment by Latitude1969** [comment]
@Tuvpt  Thnx for your responce. 
Too my understanding I'm using the latest version (2.4).
I'm on Magento 2.4.1

Could you please give me some pointers?

Thanks.

Fred.

**Comment by Tuvpt** [comment]
versions from v.4.0 and above are compatible with Magento 2.4.0
You should not try to use older versions as it may cause conflict errors

**Comment by bkkite** [comment]
@Tuvpt 
I'm getting same problem than @Latitude1969 using V.4.0 and Magento 2.4.1
If I select redirect to [coming soon page or maintenance] I see always blank page 
But If I select other page from list redirects works fine

Thanks
