### ISSUE TITLE
problem update bettermaintenance plugin from 1.0.0 to 4.0.0

### ISSUE THREAD

**Issue by yattargor** [mageplaza/magento-2-better-maintenance#19]
Hello,
According with upgrade from version 1.0.0. to 4.0.0 of mageplaza bettermaintenance plugin.

I got to the point that I have to update a Mageplaza plugin not via composer but simply by copying the folder /app and overwriting it within the webserver. After doing the usual compilations and upgrades, clear the cache as usual ... everything in the development environment works fine.

But as soon as I go to deploy in my staging environment(that is on onther webserver), and capistrano(method that I used to deploy) gives me an error at the "setup: di: compile" magento step, 

`
Tasks: TOP => magento:setup:di:compile
(See full trace by running task with --trace)
The deploy has failed with an error: Exception while executing as magento01@192.168.217.150: magento exit status: 1
magento stdout: Compilation was started.
magento stderr: %message% 0/7 [>---------------------------]   0% < 1 sec 72.5 MiB%message% 0/7 [>---------------------------]   0% < 1 sec 72.5 MiBProxies code generation... 0/7 [>------------------------]   0% < 1 sec 72.5 MiB
Proxies code generation... 1/7 [===>---------------------]  14% 2 secs 78.5 MiB
Repositories code generation... 1/7 [===>-----------------]  14% 2 secs 78.5 MiB
Repositories code generation... 2/7 [=====>-------------]  28% 14 secs 237.0 MiB
Service data attributes generation... 2/7 [===>---------]  28% 14 secs 237.0 MiB
Service data attributes generation... 3/7 [=====>-------]  42% 14 secs 239.0 MiB
Application code generator... 3/7 [=====>-------]  42% 14 secs 239.0 MiB
Application code generator... 4/7 [=======>-----]  57% 29 secs 265.0 MiB
Interceptors generation... 4/7 [=======>-----]  57% 29 secs 265.0 MiB
In Generator.php line 139:

  Class Magento\Newsletter\Model\SubscriptionManagerInterface does not exist
  Class Mageplaza\BetterMaintenance\Plugin\Controller\Subscriber\NewAction\In
  terceptor generation error: The requested class did not generate properly,
  because the 'generated' directory permission is read-only. If --- after run
  ning the 'bin/magento setup:di:compile' CLI command when the 'generated' di
  rectory permission is set to write --- the requested class did not generate
   properly, then you must add the generated class object to the signature of
   the related construct method, only.

setup:di:compile
`

I can't understand why this, I've always updated the plugins via composer this is the first time that i updated plugin via SFTP. Can you tell me how I can proceed to resolve this fail deploy?

p.s. I also update mageplaza_core with composer but nothing change

Thank you in advance for your answer

**Comment by emetik** [comment]
Hello Same issue for me. Any solution ? Thx

**Comment by Tuvpt** [comment]
Sorry for this annoyance. We have fixed this issue on brand 2.4-develop 88db119
