### ISSUE TITLE
How to customize child css

### ISSUE THREAD

**Issue by viniciusgrando** [mageplaza/magento-2-better-maintenance#2]
Hi, I was trying to customize the following path

`Magento/vendor/mageplaza/module-better-maintenance/view/frontend/web/css/style.css`

To

`Magento/app/code/mageplaza/module-better-maintenance/view/frontend/web/css/style.css`

But no working, Do you can Help me?

**Comment by bdtrung** [comment]
Hi,
I'm not sure what you mean, but if you already install the module via composer and want to move it to app/code/Mageplaza folder you should remove the old one by run these command:

`composer remove mageplaza/module-better-maintenance`
`rm -rf vendor/mageplaza/module-better-maintenance`
`composer dump-autoload`

and then download the module and paste into app/code/Mageplaza/BetterMaintenance folder

**Comment by viniciusgrando** [comment]
So, in reality, I would like to override style.css. 
Similar to how we do the theme using another main priority path

**Comment by viniciusgrando** [comment]
So, in reality, I would like to override style.css.
Similar to how we do the theme using another main priority path

**Comment by viniciusgrando** [comment]
So, in reality, I would like to override style.css.
Similar to how we do the theme using another main priority path

**Comment by bdtrung** [comment]
I'm not sure what you mean about the change in the main priority path of the theme.
Please contact the theme provider for more support.
Thanks!
