### ISSUE TITLE
Problem when installing en CE 2.3.4

### ISSUE THREAD

**Issue by calmunam** [mageplaza/magento-2-better-maintenance#20]
When installing in magento 2.3.4, entering to config admin page throws exception and the detail is:
`[2021-02-18 14:21:04] main.ERROR: Notice: Undefined index: id in /vendor/magento/module-config/Model/Config/Structure/Element/Iterator.php on line 63 [] []`
when uninstalling module config page works again.

Thanks for the help

**Comment by Tuvpt** [comment]
Sorry for this annoyance. Make sure you have the latest version of the core module
https://github.com/mageplaza/module-core
