### ISSUE TITLE
Class Magento\Newsletter\Model\SubscriptionManagerInterface does not exist                

### ISSUE THREAD

**Issue by mssyogi** [mageplaza/magento-2-better-maintenance#21]
Class Magento\Newsletter\Model\SubscriptionManagerInterface does not exist                                                                                           
  Class Mageplaza\BetterMaintenance\Plugin\Controller\Subscriber\NewAction\Interceptor generation error: The requested class did not generate properly, because the '  
  generated' directory permission is read-only. If --- after running the 'bin/magento setup:di:compile' CLI command when the 'generated' directory permission is set   
  to write --- the requested class did not generate properly, then you must add the generated class object to the signature of the related construct method, only.

**Comment by SolsWebdesign** [comment]
any solution for this? 
 Class Mageplaza\BetterMaintenance\Plugin\Controller\Subscriber\NewAction\Interceptor generation error: The requested class did not generate properly, because the 'generated' directory permission is read-only. If...
Even after disable of module

**Comment by Tuvpt** [comment]
Please grant read / write permission to the var and generate directory. Then run compile command

**Comment by SolsWebdesign** [comment]
@Tuvpt sorry that does not work. And after doing this the rough way (not recommended) I can run it once and at the next setup:upgrade the same error appears after setup:di:com. Not sure what causes it but with the extension disabled everything works fine. None of the other extensions have this problem (and I have quite a few in that shop).

**Comment by Tuvpt** [comment]
I have checked this issue and I think you are using the wrong version of the module. If you are using Magento 2.3.x, please install version 1.0.3 or version at branch 2.3

**Comment by NoDiskInDriveA** [comment]
@Tuvpt We encountered the same issue - might be a good idea to add a dependency on `magento/framework 103.*` to `composer.json` if you require Magento 2.4 on that branch?
