### ISSUE TITLE
Blank Maintenance Page and Coming soon page

### ISSUE THREAD

**Issue by tanolalano** [mageplaza/magento-2-better-maintenance#25]
I'm using it on magento 2.4.1 and Better Maintenance version is 4.0.1
If I select redirect to [coming soon page or maintenance] I see always blank page

Any thought

Thanks

**Comment by Uri-Mageplaza** [comment]
Hello,

I am Uri from Mageplaza Support Team. 

In this issue, it is possible that the default **controller_action_predispatch** event of Magento on your site has been changed.
Path: ../BetterMaintenance/etc/frontend/**events.xml**

Please try to find the changelog of this even. 
Or use another event (Example: **layout_load_before**).

Best Regards.

**Comment by tanolalano** [comment]
It works, 
using event: layout_load_before.
After changed the file used the commands: 
`setup:di:compile setup:static-content:deploy`

**Comment by DHT-Uri** [comment]
Thanks for your feedback. It's good that module is working fine.
