### ISSUE TITLE
IPv6 Support

### ISSUE THREAD

**Issue by pointia** [mageplaza/magento-2-better-maintenance#26]
To support IPv6 it would be necessary to add the following lines of code to the function \Mageplaza\BetterMaintenance\Helper\Data::ipCompare

        if (function_exists('inet_pton')) {
            return inet_pton($ip1) == inet_pton($ip2);
        }

**Comment by DHT-Uri** [comment]
Hello,

I am Uri from Mageplaza Support Team.

Thank you very much for the information you provided. 
We will review and update in the next version.

We are lucky to have you.
Best Regards!
