### ISSUE TITLE
Only show Service Temporarily Unavailable

### ISSUE THREAD

**Issue by hkvega01** [mageplaza/magento-2-better-maintenance#29]
when i've turned the website into maintenance  mode by using command "bin/magento maintenance:enable", 
but it only shows "Only show Service Temporarily Unavailable", how to make this plugin works?

**Comment by namnh112** [comment]
Hi, I'm Johan from Mageplaza.
At the moment, the Better Maintenance plugin doesn't work with maintenance mode. You need to specify a start date and end date in the plugin's configuration for it to work.
