### ISSUE TITLE
Crash the cache

### ISSUE THREAD

**Issue by angelflo** [mageplaza/magento-2-better-maintenance#3]
Hi all the team,

just a message to inform you that i discover that your extension crash the full page cache on website and so create big performance pb because when enable, the header are always define with MISS cache value and it lag alot !

after removing your better maintenance page, our wbesite will work fastly with FPC again and i can see the HIT tag in the cache header variable.

I don't know why this situation appear because i don't see cacheable="false" in your layout.xml .... but i do some test on 2 server and the result is the same => when i disable your extension , server work, when i re-enable it it lag

**Comment by bdtrung** [comment]
Please try to remove this line to solve your problem: http://i.imgur.com/ZnZMVjm.png
The file path is Mageplaza/BetterMaintenance/Block/Redirect.php
