### ISSUE TITLE
PHP incompatibility

### ISSUE THREAD

**Issue by davirs** [mageplaza/magento-2-better-maintenance#31]
This extension not works anymore. I'm running php 8

`1 exception(s):
Exception #0 (Exception): Deprecated Functionality: explode(): Passing null to parameter #2 ($string) of type string is deprecated in /public_html/vendor/mageplaza/module-better-maintenance/Block/Redirect.php on line 91
Exception #0 (Exception): Deprecated Functionality: explode(): Passing null to parameter #2 ($string) of type string is deprecated in /public_html/vendor/mageplaza/module-better-maintenance/Block/Redirect.php on line 91
<pre>#1 explode() called at [vendor/mageplaza/module-better-maintenance/Block/Redirect.php:91]
#2 Mageplaza\BetterMaintenance\Block\Redirect->getWhiteListIp() called at [vendor/mageplaza/module-better-maintenance/Observer/Redirect.php:121]
#3 Mageplaza\BetterMaintenance\Observer\Redirect->execute() called at [vendor/magento/framework/Event/Invoker/InvokerDefault.php:88]
#4 Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod() called at [vendor/magento/framework/Event/Invoker/InvokerDefault.php:74]
#5 Magento\Framework\Event\Invoker\InvokerDefault->dispatch() called at [vendor/magento/framework/Event/Manager.php:66]
#6 Magento\Framework\Event\Manager->dispatch() called at [generated/code/Magento/Framework/Event/Manager/Proxy.php:95]
#7 Magento\Framework\Event\Manager\Proxy->dispatch() called at [vendor/magento/framework/App/FrontController.php:271]
#8 Magento\Framework\App\FrontController->dispatchPreDispatchEvents() called at [vendor/magento/framework/App/FrontController.php:211]
#9 Magento\Framework\App\FrontController->processRequest() called at [vendor/magento/framework/App/FrontController.php:147]
#10 Magento\Framework\App\FrontController->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#11 Magento\Framework\App\FrontController\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#12 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php:99]
#13 Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#14 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php:71]
#15 Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#16 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#17 Magento\Framework\App\FrontController\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:23]
#18 Magento\Framework\App\FrontController\Interceptor->dispatch() called at [vendor/magento/framework/App/Http.php:116]
#19 Magento\Framework\App\Http->launch() called at [generated/code/Magento/Framework/App/Http/Interceptor.php:23]
#20 Magento\Framework\App\Http\Interceptor->launch() called at [vendor/magento/framework/App/Bootstrap.php:264]
#21 Magento\Framework\App\Bootstrap->run() called at [pub/index.php:30]
</pre>`

**Comment by KhietNguyen83** [comment]
Hi @davirs ,
I'm Justin from Mageplaza.
Please help me open the file:
- vendor/mageplaza/module-better-maintenance/Block/Redirect.php  line 91
Current code:
-   return explode(',', $this->_helperData->getWhitelistIp() );
Edit to:
-  return explode(',', $this->_helperData->getWhitelistIp() ?? '' );
Thank you very much!
