### ISSUE TITLE
Maintenance page shows at down below actual homepage

### ISSUE THREAD

**Issue by hitendra52** [mageplaza/magento-2-better-maintenance#4]
Hi,

We encountered the issue when we enabled the maintenance page.
Maintenance page is showing below actual page and not hiding pages
![screencapture-schools365-in-2020-02-13-02_26_51](https://user-images.githubusercontent.com/5452177/74376620-7baf1c80-4e08-11ea-8e5b-ee972f6f112d.png)

**Comment by toandt98** [comment]
First of all, thank you for contacting us. 
I'm Uri from Mageplaza Support Team. Please let me assist you on this issue.

Through the information you provided, maybe the problem stemmed from the theme.
The individual blocks created by each theme create a module that does not define those blocks. 

If you are a developer, please search for the corresponding blocks and remove them. Or you can create a ticket here: https://mageplaza.freshdesk.com/
We can remove it for you.

Best Regards
