### ISSUE TITLE
Show template frame

### ISSUE THREAD

**Issue by zerod10** [mageplaza/magento-2-better-maintenance#5]
The page I create is inside the template frame, i need to show only the coming soon page not my menu or other parts of the work in progress site, has can I fix that?
![Uploading Schermata 2020-02-25 alle 19.34.25.png…](screenshot)

**Comment by toandt98** [comment]
First of all, thank you for contacting us.
I'm Uri from Mageplaza Support Team. Please let me assist you on this issue.

Through the information you provided, maybe the problem stemmed from the theme.
The individual blocks created by each theme create a module that does not define those blocks.

If you are a developer, please search for the corresponding blocks and remove them. Or you can create a ticket here: https://mageplaza.freshdesk.com/
We can remove it for you.

Best Regards
