### ISSUE TITLE
Blank admin page

### ISSUE THREAD

**Issue by schadedk** [mageplaza/magento-2-better-maintenance#6]
I tried to install the product following the guide.

I have a new page at "Stores > Configuration > Mageplaza > Better Maintenance" but the page is empty.

I checked all my log-files. Nothing there.

![magento_blank_page](https://user-images.githubusercontent.com/4639222/82751491-e7b20100-9db7-11ea-9d49-cd3011fc4f84.png)

What could be wrong?

**Comment by toandt98** [comment]
Hello,
I'm Uri from Mageplaza Support Team.

Please replace the attached file with the link:
- /app/code/Mageplaza/BetterMaintenance/etc/adminhtml/system.xml

(link attach file: https://drive.google.com/file/d/1CPguPq6XBrZNMKvWAeJ-UcFGOPEQI-dJ/view?usp=sharing)

Then flush the cache and check again.

Hope it helps you fix the problem!
Best Regards,
Uri

**Comment by schadedk** [comment]
Hi Uri,

That did it - thanks

One small difference - my folder was located in the in  /vendor/

Thanks,
René

**Comment by breakerh** [comment]
I also got this issue in `Magento ver. 2.3.5-p1` with a fresh install of both magento and the module.
I do however got the single mode on. Is this the reason? I saw the multi background element commented out with the altered version.

So i think this particular case is solved however more people experience this problem right?
