### ISSUE TITLE
addSessionParam() called at Block/Adminhtml/System/Renderer/Images.php:98 - Magento 2.3.5-pl

### ISSUE THREAD

**Issue by maxlatitude** [mageplaza/magento-2-better-maintenance#7]
Session parameters deprecated in Magento 2.3.5-pl. Exception error on Better-Maintenance:

addSessionParam() called at Block/Adminhtml/System/Renderer/Images.php:98

**Comment by Tuvpt** [comment]
Thank you for contacting us!
We have received your notice and have fixed this issue.
Please refer this commit
https://github.com/mageplaza/magento-2-better-maintenance/commit/207b40e7c53d3e62dea00d592c30f493dd055277
